version: "3"

services:
  gateway:
    restart: always
    image: app/gateway:latest
    command: gow run cmd/gateway/main.go
    build:
      context: ./
      dockerfile: ./cmd/gateway/Dockerfile
    ports:
      - 1323:1323
    volumes:
      - "./:/go/src/app:ro"