// GENERATED BY metatag, DO NOT EDIT
// (or edit away - I'm a comment, not a cop)

package crud

// GetID returns the value of ID.
func (m Model) GetID() uint {
	return m.ID
}

// GetUUID returns the value of UUID.
func (m Model) GetUUID() string {
	return m.UUID
}
