// GENERATED BY metatag, DO NOT EDIT
// (or edit away - I'm a comment, not a cop)

package crud

// GetPk returns the value of ID.
func (m Model) GetPk() uint64 {
	return m.Pk
}

// GetID returns the value of UUID.
func (m Model) GetID() string {
	return m.ID
}
