// GENERATED BY metatag, DO NOT EDIT
// (or edit away - I'm a comment, not a cop)

package entity

// GetName returns the value of Name.
func (f FormTemplate) GetName() string {
	return f.Name
}

// SetName sets the given value as Name.
func (f *FormTemplate) SetName(s string) {
	f.Name = s
}
